modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Vazkii/Neat"
license="Creative Commons 3.0 BY-NC-SA"

[[mods]]
modId="neat"
displayName="Neat"
version="${file.jarVersion}"
authors="Vazkii"
description='''
Minimalistic Functional Unit Plates for the modern Minecrafter
'''
